const express = require("express");
const db = require('./config/db-config')
const PORT = process.env.PORT||5500;
const indexRouter = require("./routes/index");
const usersRouter = require("./routes/users");
const registerRouter = require("./routes/register");
const loginRouter = require("./routes/login");
const contactRouter = require("./routes/contact");
const reviewRouter = require("./routes/review");
const photoRouter = require("./routes/photo");
const imageRouter = require("./routes/image");
const app = express();
app.set("view engine", "ejs");
app.set(db);
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(express.static("public"));
app.use(indexRouter);
app.use(usersRouter);
app.use(registerRouter);
app.use(loginRouter);
app.use(contactRouter);
app.use(reviewRouter);
app.use(photoRouter);
app.use('/image',imageRouter);
app.listen(PORT, () => console.log(`Server listening to port ${PORT}`));